version = 0.1
[default.deploy.parameters]
stack_name = "todo-app"
resolve_s3 = true
s3_prefix = "todo-app"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
